- id : doi.org/10.1039/D5TA01703C
  type:
  image : https://pubs.rsc.org/image/article/2025/ta/d5ta01703c/d5ta01703c-f4_hi-res.gif
  description:

- id : doi:10.1021/jacs.4c15674
  type:
  image : https://pubs.acs.org/cms/10.1021/jacs.4c15674/asset/images/large/ja4c15674_0004.jpeg
  description:

- id : doi:10.1002/smll.202410079
  type:
  image : https://onlinelibrary.wiley.com/cms/asset/a3e30952-fe88-4e78-bb80-5708783e8d0b/smll202410079-fig-0004-m.jpg
  description:

- id: doi:10.1002/adma.202409906
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/2a054a72-ef21-4226-909c-154d55c35f2f/adma202409906-gra-0001-m.jpg?trick=1734349701092
  description: 

- id: doi:10.1002/advs.202309786
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/ab1c947b-015b-4795-8024-986abd6a06cd/advs8338-fig-0007-m.jpg
  description: 

- id: doi:10.1002/adma.202204272
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/2cd08bb9-5475-484e-a661-128fc8de2262/adma202204272-gra-0001-m.jpg
  description: Perspective article

- id: doi:10.1002/adma.202203413
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/950b3417-1493-489f-809c-5041f5bee2b7/adma202203413-gra-0001-m.jpg
  description:
  
- id: doi:10.1002/adma.202303655
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/fdb63c21-0885-4d86-bddf-bd4ba75ed8fd/adma202303655-gra-0001-m.jpg
  description:
  
- id: doi:10.1002/ange.202303890
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/61ee97e3-34c9-4678-af54-f40af80efb18/ange202303890-toc-0001-m.jpg
  description:
  
- id: doi:10.1126/sciadv.abq6207
  type: 
  image: https://www.science.org/cms/10.1126/sciadv.abq6207/asset/a61c3f68-e661-4b33-a091-465caa8bd187/assets/images/large/sciadv.abq6207-f1.jpg
  description:

- id: doi:10.1002/aelm.202201293
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/4902a23e-da78-4597-b08b-73c7aef28541/aelm202201293-gra-0001-m.jpg
  description: 

- id: doi:10.1038/s41467-022-31400-6
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-31400-6/MediaObjects/41467_2022_31400_Fig1_HTML.png?
  description: 

- id: doi:10.1021/acs.macromol.1c02461
  type:
  image: https://pubs.acs.org/cms/10.1021/acs.macromol.1c02461/asset/images/medium/ma1c02461_0008.gif
  description: 

- id: doi:10.1038/s41586-021-04391-5
  type: 
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41586-021-04391-5/MediaObjects/41586_2021_4391_Fig2_HTML.png?
  description: 

- id: doi:10.1073/pnas.2107987118
  type: 
  image: https://www.pnas.org/cms/10.1073/pnas.2107987118/asset/b6242ecf-f37a-4163-b7a3-59729847855c/assets/images/large/pnas.2107987118fig01.jpg
  description: 

- id: doi:10.1002/anie.202103827
  type: 
  image: https://onlinelibrary.wiley.com/cms/asset/fae32b3d-9f09-4463-b833-a7191f8e7b64/anie202103827-toc-0001-m.jpg
  description: 

- id: doi:10.1073/pnas.2020615118
  type: 
  image: https://www.pnas.org/cms/10.1073/pnas.2020615118/asset/b928b18c-674c-4716-9cdb-414b7e9316ed/assets/images/large/pnas.2020615118fig01.jpg
  description: 

- id: doi:10.1063/5.0016163
  type: 
  image: https://aipp.silverchair-cdn.com/aipp/content_public/journal/jcp/153/10/10.1063_5.0016163/5/m_100903_1_5.0016163.figures.online.f1.jpeg?Expires=1724236279&Signature=X6rOlumSIpa~rw7qtHVvITMvcucBECzUNTwUfRDU6aDHCSnGSPRbZRVyI0TYUOKWJjJux0DmLXDApxsBQUlrgVLGve3AkvTXyXMPBiH1X4n9I0Vy~LQtzalZxyAcfwxujGbtn3Jw6-IsNc35RZvEUKUv7xs3amjRNC-ZXGLpfEYzigQvy0sPQz9opihWlI4HElJd8YzhWrH8wtuvSCugn0iXx--fqQMGMKbxLfTwpCF-hkKpPjgZCWYFvQirWqRVjB31fBVet3u~7cyTOxRisMBjh47-hvKlnm5tmgxWmexe8nus9HZHKPv9kcIvTUz0UE~6Yy44nTeEm-sk7N7fXg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  description: 

- id: doi:10.1021/acs.langmuir.0c01369
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.langmuir.0c01369/asset/images/medium/la0c01369_0007.gif
  description: 

- id: doi:10.1016/j.bbabio.2020.148239
  type: 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S000527282030089X-gr1.jpg
  description: 

- id: doi:10.1021/acs.jpclett.9b02983
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpclett.9b02983/asset/images/medium/jz9b02983_0005.gif
  description: 

- id: doi:10.1021/acs.macromol.8b01002
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.macromol.8b01002/asset/images/medium/ma-2018-010024_0013.gif
  description: 

- id: doi:10.1021/acs.jpcb.8b04886
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcb.8b04886/asset/images/medium/jp-2018-04886z_0008.gif
  description: 

- id: doi:10.1016/j.bbabio.2018.05.010
  type: 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0005272818301257-gr1.jpg
  description: 

- id: doi:10.1021/acs.jpcb.8b01221
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcb.8b01221/asset/images/medium/jp-2018-01221d_0014.gif
  description: 

- id: doi:10.1073/pnas.1707922114
  type: 
  image: 
  description: 

- id: doi:10.1021/acs.jpcb.5b12371
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcb.5b12371/asset/images/medium/jp-2015-123714_0009.gif
  description: 

- id: doi:10.1021/acs.jpcb.6b05328
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcb.6b05328/asset/images/medium/jp-2016-05328u_0010.gif
  description: 

- id: doi:10.1039/C5AN00835B
  type: 
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C5AN00835B&imageInfo.ImageIdentifier.Year=2016
  description: 

- id: doi:10.1021/acs.jpcb.5b10065
  type: 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcb.5b10065/asset/images/medium/jp-2015-10065s_0013.gif
  description: 

- id: doi:10.1063/1.4802584
  type: 
  image: 
  description: 

- id: doi:10.1063/1.3665415
  type: 
  image: 
  description: 

- id: doi:10.1063/1.3565476
  type: 
  image: 
  description: 

- id: doi:10.1103/PhysRevE.83.041201
  type: 
  image: 
  description:
